### ISSUE TITLE
Engine Request: RSDKv3

### ISSUE THREAD

**Issue by tuxpengu** [dreamer/luxtorpeda#101]
* Is this project listed as [a candidate](https://github.com/dreamer/luxtorpeda/wiki/Game-engines) already?: No
* Project link: [Rubberduckycooly/Sonic-CD-11-Decompilation](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation)
* Project license: [License](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/blob/master/LICENSE.md)
* Does it work on 64-bit only Linux: Yes
* Is source code available?: Yes
* Is source code stored in Git?: Yes
* List of Steam AppIds of supported games:
[Sonic CD](https://steamdb.info/app/200940/)

## Additional information

The game is no longer available to buy on Steam

The decompiled engine depends on the `Data.rsdk` file and `videos` folder inside the installation folder to function

**Comment by JoshuaFern** [comment]
You are in the old repo. 

https://github.com/luxtorpeda-dev/packages/issues/678
