### ISSUE TITLE
Keyboard not working in game

### ISSUE THREAD

**Issue by XLRUUU** [dreamer/luxtorpeda#102]
Hello,

I have a problem using the Steam Deck virtual keyboard in game, 

When in game, typing on the keyboard doesn't work, for example, writing save names, chat or using the game console.

I've got this issue in multiple games like Doom 3 (using the Dhewm3 source port), Doom (using GZDoom, QZDL) but it seems to work in the QZDL interface before launching the game.

I'm not sure if this a Luxtorpeda issue or a SteamOS one.

Thanks.

**Comment by ghost** [comment]
Hi, you happen to have posted in the wrong place. This is the old, currently maintained version of Luxtorpeda. The Luxtorpeda-dev repo is probably where you want to be.

https://github.com/luxtorpeda-dev/luxtorpeda
