### ISSUE TITLE
Steam Deck: Error on run: Path to Steam Linux Runtime not given.

### ISSUE THREAD

**Issue by Renari** [dreamer/luxtorpeda#108]
**Describe the bug**
When trying to run a game using nw.js I get the error `Error on run: Path to Steam Linux Runtime not given`.  I don't see anywhere to configure this and reading through the config guide and the wiki I'm not finding anything that says how or where you should configure this path.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install steam linux runtime sniper
2. Try to launch game with nw.js
3. claims it cannot find runtime

**Comment by ghost** [comment]
This is the original repo for Luxtorpeda, try here instead: https://github.com/luxtorpeda-dev/packages
