### ISSUE TITLE
Jagged Alliance 2 Gold not being detected propertly...

### ISSUE THREAD

**Issue by troop711** [dreamer/luxtorpeda#109]
**Describe the bug**
When trying to use luxtropeda on Jagged Alliance 2 Gold, it asks me what engine to use with no option being [Stracciatella](https://ja2-stracciatella.github.io/)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Jagged Alliance 2 Gold on steam deck
2. Change launcher to use luxtropeda
3. Run the game

**Expected behaviour**
Game should install [Stracciatella](https://ja2-stracciatella.github.io/) automatically.

**Comment by ghost** [comment]
This is the original repo for Luxtorpeda, try here instead: https://github.com/luxtorpeda-dev/packages
