### ISSUE TITLE
List of games that can be added to luxtorpeda or boxtron

### ISSUE THREAD

**Issue by monyarm** [dreamer/luxtorpeda#11]
https://steam.fandom.com/wiki/List_of_DRM-free_games

This wiki has a list of games that use DosBox, a list of games that are just a SWF file and an included SWF player, a list of games that are a rom file and included emulator. Also another one i can think of is Spiral Knights, which if i remember correctly is a browser game and included browser.

Once you write a tutorial on how to create a package, i'll gladly package the games i own.

**Comment by dreamer** [comment]
Initial, very work-in-progress version of packaging tutorial started to appear on wiki: https://github.com/dreamer/luxtorpeda/wiki/Packaging-tutorial

We are documenting any DOSBox game we find on "Powered by DOSBox" curator page: https://store.steampowered.com/curator/35328265-Powered-by-DOSBox/ - I guess someone needs to comb through both lists to see if we missed any ;)

Regarding SWF files (I presume these are titles that originally used Flash - like e.g. Samorost or Adobe Air games) - which player do you suggest? I am not sure if I own any of these games, I'll need to check.

BTW, we are documenting engines and software that can be used for specific Steam titles on this wiki page: https://github.com/dreamer/luxtorpeda/wiki/Game-engines - feel free to add new entries to "List of candidates" table.

**Comment by monyarm** [comment]
Great, i'll do that after work today, and ya the SWF files are games made in flash, some of them have linux versions, but alot don't, however can be played just fine in either a browser or in Adobe Flash Player Projector.

**Comment by dreamer** [comment]
Seems like Linux version of Adobe Flash Player Projector is still supported, includes 64-bit version and is available for download: https://www.adobe.com/support/flashplayer/debug_downloads.html - interesting! We obviously can't recompile it for Steam Runtime, but maybe it will work nonetheless.

**Comment by dreamer** [comment]
I added information about Adobe Flash Player Projector and steam.fandom.com list of games to the https://github.com/dreamer/luxtorpeda/wiki/Game-engines

Otherwise, there are no specific Steam AppIds here - this issue is non-actionable, so I am closing it.
