### ISSUE TITLE
Consider using ASFMirror

### ISSUE THREAD

**Issue by neuromancer** [dreamer/luxtorpeda#30]
https://a-sf-mirror.github.io/
https://github.com/a-sf-mirror

(We could try to contact the authors to add git mirrors of selected engines)

**Comment by dreamer** [comment]
I already have started some work in the same area in https://github.com/subversioned-upstream

It seems like asfmirror projects does only one-time dumps of code, which is not good enough for maintaining the package. Good to know about this project, I might contact them in order to cooperate.
