### ISSUE TITLE
Return to Castle Wolfenstein (9010) - Working Package

### ISSUE THREAD

**Issue by d10sfan** [dreamer/luxtorpeda#4]
This adds support for RTCW through the IORTCW engine: https://gitlab.com/d10sfan/luxtorpeda-iortcw

Steam downloads the game with a Main directory (probably because of Windows pathing issues), so that's why the build points it there. Also, there's a command line argument to point it to "Main" instead of "main". No changes are needed to the actual original steam files though.

The packages.json addition looks like the following:

```
        "9010": {
		"game_name":    "Return to Castle Wolfenstein",
		"package":      "dist.tar.xz",
		"command":      "./iowolfsp.x86_64",
		"command_args": ["+set", "com_basegame", "Main"]
	}
```

For this one, there's two options when you launch it through steam, Single Player or Multiplayer. This builds both and both seem to work if you run them manually, but I don't see a way through this tool of defining one or the other. SteamDB shows the two different exes it normally tries to load: https://steamdb.info/app/9010/config. I'm thinking for this, maybe if there's some way of detecting which option is selected, and then having an additional argument in the packages.json to tell it which command to use for which option. For now, SP is default and does seem to work.

**Comment by dreamer** [comment]
Done; it went smoother this time due to your repo sitting on GitLab :) I gave you developer role for package repo, same as for Doom 3.

Once you'll confirm it's works for both SP and MP, I will close this issue.

**Comment by d10sfan** [comment]
Yep, both mp and sp worked with the new build and the hosted built version.
