### ISSUE TITLE
Request for Quake 1 Mission Packs being packaged

### ISSUE THREAD

**Issue by CardboardTurtle** [dreamer/luxtorpeda#71]
https://steamdb.info/app/9040
https://steamdb.info/app/9030

they're listed as "TBD" as to when they'll be packaged at the moment.

**Comment by StoneyFish** [comment]
It would be very nice if you could package the Quake missions up.
Quake with luxtorpeda is great.
I tried to start these missions with proton and I get black screen at the start , needed to Alt-Tab out and back in.  In the standard version there is no 1920x1080 option. In the GL version the option menus are just white blocks.

**Comment by d10sfan** [comment]
If you're interested, this is done in the luxtorpeda-dev fork - https://github.com/luxtorpeda-dev/luxtorpeda

**Comment by StoneyFish** [comment]
The luxtorpeda-dev fork is working great with both mission pack games. And the choices of vkquake, darkplaces-2017 or quakespasm-spiked all seem to work.  Very nice.  Thank you for making Linux gaming easier to do.
