### ISSUE TITLE
Update OpenMW package to version 0.46

### ISSUE THREAD

**Issue by FurtadoPires** [dreamer/luxtorpeda#77]
* Project link: https://github.com/OpenMW/openmw
* Does it work on 64-bit only Linux: Yes
* Is source code available?: Yes
* Is source code stored in Git?: Yes
 https://steamdb.info/app/22320
## Additional information
I would like to request the update of OpenMW inside Luxtorpeda. The project is currently at version 0.46.0 while Luxtorpeda is using 0.45.0

**Comment by d10sfan** [comment]
If you're interested, I have a fork here: https://github.com/luxtorpeda-dev/luxtorpeda

This has an updated openmw along with other games
