### ISSUE TITLE
Update dxx-rebirth (D1 and D2) to latest (protocol mismatch on multiplayer games)

### ISSUE THREAD

**Issue by agibson2** [dreamer/luxtorpeda#89]
Dxx-rebirth has published a new Windows build on their website where they changed the multiplayer protocol.  The current Luxtorpeda dxx-rebirth for D1 and D2 multiplayer is now not compatible with the officially published dxx-rebirth windows build.  Any change to get it updated again?  Please :).

**Comment by d10sfan** [comment]
@agibson2 This repo is not maintained. Are you referring to luxtorpeda-dev?

If so, could you create an issue in the packages repo (luxtorpeda-dev/packages) with the version/commit hash of what you are wanting?

**Comment by agibson2** [comment]
Yes sorry.  I made a similar mistake last time but it was at least on the correct github(not Dreamer).  I will put the request on packages and the correct repo instead of Dreamer.
